name: test_parking_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  integration_test:
    sdk: flutter
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  bloc_test: ^9.1.6
  flutter_modular: ^6.3.2
  intl: ^0.19.0
  core_network:
    path: core_network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true